using System.Text.Json.Serialization;

namespace NuttyTree.NetDaemon.ExternalServices.Unifi.Models;

public sealed class WirelessNetwork
{
    [JsonPropertyName("_id")]
    public string? Id { get; set; }

    public string? Name { get; set; }

    [JsonPropertyName("x_passphrase")]
    public string? Passphrase { get; set; }

    [JsonPropertyName("setting_preference")]
    public string? SettingPreference { get; set; }

    [JsonPropertyName("dtim_6e")]
    public int Dtim6e { get; set; }

    [JsonPropertyName("wpa3_support")]
    public bool Wpa3Support { get; set; }

    [JsonPropertyName("minrate_na_advertising_rates")]
    public bool MinrateNaAdvertisingRates { get; set; }

    [JsonPropertyName("wpa_mode")]
    public string? WpaMode { get; set; }

    [JsonPropertyName("minrate_setting_preference")]
    public string? MinrateSettingPreference { get; set; }

    [JsonPropertyName("minrate_ng_advertising_rates")]
    public bool MinrateNgAdvertisingRates { get; set; }

    [JsonPropertyName("b_supported")]
    public bool BSupported { get; set; }

    [JsonPropertyName("radius_das_enabled")]
    public bool RadiusDasEnabled { get; set; }

    [JsonPropertyName("group_rekey")]
    public int GroupRekey { get; set; }

    [JsonPropertyName("radius_macacl_format")]
    public string? RadiusMacaclFormat { get; set; }

    //[JsonPropertyName("")]
    //public string? pmf_mode { get; set; }

    //[JsonPropertyName("")]
    //public bool wpa3_transition { get; set; }

    //[JsonPropertyName("")]
    //public bool passphrase_autogenerated { get; set; }

    //[JsonPropertyName("")]
    //public object[] private_preshared_keys { get; set; }

    //[JsonPropertyName("")]
    //public bool mcastenhance_enabled { get; set; }

    //[JsonPropertyName("")]
    //public string? usergroup_id { get; set; }

    //[JsonPropertyName("")]
    //public bool proxy_arp { get; set; }

    //[JsonPropertyName("")]
    //public int sae_sync { get; set; }

    //[JsonPropertyName("")]
    //public bool uapsd_enabled { get; set; }

    //[JsonPropertyName("")]
    //public bool iapp_enabled { get; set; }

    //[JsonPropertyName("")]
    //public string? radiusprofile_id { get; set; }

    //[JsonPropertyName("")]
    //public string? site_id { get; set; }

    //[JsonPropertyName("")]
    //public bool hide_ssid { get; set; }

    //[JsonPropertyName("")]
    //public string? wlan_band { get; set; }

    //[JsonPropertyName("")]
    //public bool private_preshared_keys_enabled { get; set; }

    //[JsonPropertyName("")]
    //public bool no2ghz_oui { get; set; }

    //[JsonPropertyName("")]
    //public string? x_iapp_key { get; set; }

    //[JsonPropertyName("")]
    //public string? networkconf_id { get; set; }

    //[JsonPropertyName("")]
    //public int dtim_na { get; set; }

    //[JsonPropertyName("")]
    //public bool is_guest { get; set; }

    //[JsonPropertyName("")]
    //public bool minrate_na_enabled { get; set; }

    //[JsonPropertyName("")]
    //public object[] sae_groups { get; set; }

    //[JsonPropertyName("")]
    //public bool enabled { get; set; }

    //[JsonPropertyName("")]
    //public object[] sae_psk { get; set; }

    //[JsonPropertyName("")]
    //public string[] wlan_bands { get; set; }

    //[JsonPropertyName("")]
    //public string? mac_filter_policy { get; set; }

    //[JsonPropertyName("")]
    //public string? security { get; set; }

    //[JsonPropertyName("")]
    //public string[] ap_group_ids { get; set; }

    //[JsonPropertyName("")]
    //public bool l2_isolation { get; set; }

    //[JsonPropertyName("")]
    //public bool minrate_ng_enabled { get; set; }

    //[JsonPropertyName("")]
    //public bool bss_transition { get; set; }

    //[JsonPropertyName("")]
    //public int minrate_ng_data_rate_kbps { get; set; }

    //[JsonPropertyName("")]
    //public bool radius_mac_auth_enabled { get; set; }

    //[JsonPropertyName("")]
    //public bool wpa3_fast_roaming { get; set; }

    //[JsonPropertyName("")]
    //public object[] schedule_with_duration { get; set; }

    //[JsonPropertyName("")]
    //public string? ap_group_mode { get; set; }

    //[JsonPropertyName("")]
    //public bool wpa3_enhanced_192 { get; set; }

    //[JsonPropertyName("")]
    //public bool fast_roaming_enabled { get; set; }

    //[JsonPropertyName("")]
    //public string? wpa_enc { get; set; }

    //[JsonPropertyName("")]
    //public string[] mac_filter_list { get; set; }

    //[JsonPropertyName("")]
    //public string? dtim_mode { get; set; }

    //[JsonPropertyName("")]
    //public object[] schedule { get; set; }

    //[JsonPropertyName("")]
    //public object[] bc_filter_list { get; set; }

    //[JsonPropertyName("")]
    //public int minrate_na_data_rate_kbps { get; set; }

    //[JsonPropertyName("")]
    //public bool mac_filter_enabled { get; set; }

    //[JsonPropertyName("")]
    //public int sae_anti_clogging { get; set; }

    //[JsonPropertyName("")]
    //public int dtim_ng { get; set; }

    //[JsonPropertyName("")]
    //public bool bc_filter_enabled { get; set; }
}
