// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuttyTree.NetDaemon.Infrastructure.Database;

#nullable disable

namespace NuttyTree.NetDaemon.Infrastructure.Database.Migrations
{
    [DbContext(typeof(NuttyDbContext))]
    partial class NuttyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("NuttyTree.NetDaemon.Infrastructure.Database.Entities.AppointmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calendar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Person")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("NuttyTree.NetDaemon.Infrastructure.Database.Entities.AppointmentReminderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArriveLeadMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnnouncementTypes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAnnouncement")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAnnouncement")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextAnnouncementType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextTravelTimeUpdate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TravelMiles")
                        .HasColumnType("REAL");

                    b.Property<double?>("TravelMinutes")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentReminders");
                });

            modelBuilder.Entity("NuttyTree.NetDaemon.Infrastructure.Database.Entities.AppointmentReminderEntity", b =>
                {
                    b.HasOne("NuttyTree.NetDaemon.Infrastructure.Database.Entities.AppointmentEntity", "Appointment")
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("NuttyTree.NetDaemon.Infrastructure.Database.Entities.AppointmentEntity", b =>
                {
                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
