<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS0436</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.12" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.12" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NuttyTree.NetDaemon.Application\NuttyTree.NetDaemon.Application.csproj" />
  </ItemGroup>

</Project>
